name: Push
on: push
env:
  APP: flex-static-files
jobs:
  build-and-publish:
    name: Bygg, test og publiser docker image
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.lag-image.outputs.image }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - name: Generer image
        id: lag-image
        run: |
          TIME=$(TZ="Europe/Oslo" date +%Y.%m.%d-%H.%M)
          COMMIT=$(git rev-parse --short=8 HEAD)
          VERSION=$TIME-$COMMIT
          echo "::set-output name=image::ghcr.io/navikt/$APP:$VERSION"
      - name: Install npm dependencies
        run: npm ci
      - name: Run lint
        run: npm run lint
      - name: Build server
        run: npm run build

      - name: Docker login
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        if: github.ref_name == 'master' || startsWith(github.ref_name, 'dev-')
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Bygg og push Docker image
        if: github.ref_name == 'master' || startsWith(github.ref_name, 'dev-')
        run: |
          docker build . -f Dockerfile -t ${{ steps.lag-image.outputs.image }}
          docker push ${{ steps.lag-image.outputs.image }}

  snyk-npm:
    needs: build-and-publish
    uses: navikt/flex-github-actions-workflows/.github/workflows/snyk-npm.yml@master
    secrets: inherit

  snyk-docker:
    needs: build-and-publish
    uses: navikt/flex-github-actions-workflows/.github/workflows/snyk-docker.yml@master
    with:
      image: ${{ needs.build-and-publish.outputs.image }}
    secrets: inherit

  nais-deploy:
    needs: build-and-publish
    uses: navikt/flex-github-actions-workflows/.github/workflows/nais-deploy-dev-og-prod.yml@master
    with:
      image: ${{ needs.build-and-publish.outputs.image }}
      app: ${{ inputs.app }}
    secrets: inherit
